name: project3
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain
      - langgraph
      - pydantic
      - openai
      - langchain-core
      - langchain-community
      - faiss-cpu
      - uvicorn
      - fastapi
      - pillow           
      - python-dotenv    
